Godot 3.2 error update
In the newly released Godot 3.2, InkStory.cs spits back the following error:
```
addons/paulloz.ink/InkStory.cs(242,19): error CS1503: Argument 2: cannot convert from 'int' to 'Godot.File.ModeFlags' 
addons/paulloz.ink/InkStory.cs(263,19): error CS1503: Argument 2: cannot convert from 'int' to 'Godot.File.ModeFlags'
```
Just removing the (int) cast from lines 242 and 263 seems to fix the issue. I'm not sure if this fix is backwards-compatible with earlier versions of Godot, however.